# src/methods/writer_only_v3_method.py
"""
WriterOnlyV3 Method - Simplified single-agent method with enhanced WriterV3 agent.

This method implements the hybrid architecture design using only WriterV3 agent
without any reviewer collaboration. WriterV3 provides enhancements over WriterV2
with improved research context tracking and refined workflows.
"""

import time

import logging

from src.collaborative.agents.writer_v4 import WriterV4
from src.collaborative.memory.memory import SharedMemory
from src.config.config_context import ConfigContext
from src.methods.base_method import BaseMethod
from src.utils.data import Article
from src.utils.text_processing import remove_citation_tags

logger = logging.getLogger(__name__)


class WriterOnlyV3Method(BaseMethod):
    """
    Single WriterV3 agent method with hybrid architecture.

    Features:
    - Hybrid architecture: Python orchestration + LLM content generation
    - Enhanced WriterV3 with improved research context handling
    - Deterministic workflow for predictable execution
    - No collaboration complexity - pure writing focus
    - Clear error handling with no fallbacks

    Workflow:
    - WriterV3 executes iteration 0 workflow only:
      direct_search(topic) → generate_queries(top_chunk) → search_queries →
      create_outline(top_chunk) → write_all_sections(chunks)
    """

    def __init__(self):
        super().__init__()

    def run(self, topic: str) -> Article:
        """
        Run WriterV3-only method for article generation.

        Args:
            topic: Topic to write about

        Returns:
            Generated article with WriterV3 metadata
        """
        logger.info(f"Running WriterV3-only method for: {topic}")

        # Reset usage counters at start
        task_models = self._get_task_models_for_method()
        self._reset_all_client_usage(task_models)

        start_time = time.time()

        try:
            # Get experiment output directory from ConfigContext
            output_dir = ConfigContext.get_output_dir()

            # Initialize shared memory (no collaboration features needed)
            memory = SharedMemory(
                topic=topic,
                storage_dir=output_dir,  # Store memory files in experiment dir
                tom_enabled=False,  # No collaboration, so no ToM needed
                experiment_name="writer_only_v3",
            )

            # Set memory instance for tools and agent to access
            ConfigContext.set_memory_instance(memory)

            # Initialize WriterV3 agent
            writer = WriterV4()

            # Initialize article state in memory
            seed_article = Article(
                title=topic,
                content=f"# {topic}\n\n",
                sections={},
                metadata={"method": "writer_only_v3"},
            )
            memory.update_article_state(seed_article)

            # WriterV3 executes iteration 0 workflow (research and write)
            logger.info(f"WriterV3 creating article for: {topic}")
            writer_start = time.time()

            try:
                writer.process()  # Will execute iteration 0 workflow
                writer_time = time.time() - writer_start
                logger.info("WriterV3 completed article creation")
            except Exception as e:
                logger.error(f"WriterV3 failed: {e}")
                raise RuntimeError(f"WriterV3 failed: {e}") from e

            # Get final article from memory
            final_draft = memory.get_current_draft()
            if not final_draft:
                raise RuntimeError("No final article generated by WriterV3")

            # Get current sections
            current_iteration = memory.get_iteration()
            sections = memory.get_sections_by_iteration(current_iteration)
            if not sections:
                sections = {}

            # Collect token usage statistics
            token_usage = self._collect_token_usage(task_models)

            # Build final article with comprehensive metadata
            total_time = time.time() - start_time

            final_article = Article(
                title=topic,
                content=final_draft,
                sections=sections,
                metadata={
                    # Standard metadata fields expected by output_manager
                    "generation_time": total_time,
                    "model": getattr(writer.api_client, "model_path", "unknown"),
                    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                    # Method-specific metadata
                    "method": "writer_only_v3",
                    "agent_version": "v3",
                    "workflow_type": "hybrid_deterministic",
                    "total_iterations": 1,
                    "execution_time": total_time,
                    "detailed_timing": {
                        "total_time": total_time,
                        "writer_time": writer_time,
                        "overhead_time": total_time - writer_time,
                    },
                    "content_metrics": {
                        "character_count": len(final_draft),
                        "section_count": len(sections),
                        "word_count": len(final_draft.split()) if final_draft else 0,
                    },
                    "research_metrics": self._get_research_metrics(memory),
                    "token_usage": token_usage,
                },
            )

            logger.info("WriterV3-only method completed successfully")
            logger.info(
                f"Final article: {len(final_article.content)} characters, {len(final_article.sections)} sections"
            )
            logger.info(
                f"Total time: {total_time:.2f}s, tokens: {token_usage['total_tokens']}"
            )

            # Post-processing: Remove citation tags before final output
            final_article.content = remove_citation_tags(final_article.content)

            return final_article

        except Exception as e:
            logger.error(f"WriterV3-only method failed: {e}", exc_info=True)
            raise RuntimeError(f"WriterOnlyV3Method failed: {e}") from e

    def _get_research_metrics(self, memory: SharedMemory) -> dict:
        """Get research metrics from memory."""
        try:
            stored_chunks = memory.get_stored_chunks()
            search_summaries = memory.get_search_summaries()

            return {
                "total_chunks": len(stored_chunks),
                "total_searches": len(search_summaries),
                "chunk_sources": list(
                    set(
                        chunk.source
                        for chunk in stored_chunks
                        if hasattr(chunk, "source")
                    )
                ),
                "average_chunk_length": (
                    sum(len(chunk.content) for chunk in stored_chunks)
                    / len(stored_chunks)
                    if stored_chunks
                    else 0
                ),
            }
        except Exception as e:
            logger.warning(f"Could not calculate research metrics: {e}")
            return {"error": str(e)}
