# FILE: runners/runner_utils.py
from pathlib import Path

import logging

from baselines.llm_wrapper import OllamaLiteLLMWrapper
from config.model_config import ModelConfig
from utils.data_models import Article
from utils.ollama_client import OllamaClient

logger = logging.getLogger(__name__)


def get_model_wrapper(
    client: OllamaClient, config: ModelConfig, task: str
) -> OllamaLiteLLMWrapper:
    model = config.get_model_for_task(task)
    temp = config.get_temperature_for_task(task)
    max_tokens = config.get_token_limit_for_task(task)
    return OllamaLiteLLMWrapper(
        ollama_client=client, model=model, temperature=temp, max_tokens=max_tokens
    )


def build_direct_prompt(topic: str) -> str:
    return f"""Write a comprehensive, well-structured Wikipedia-style article about \"{topic}\".

Requirements:
1. Create a detailed article with multiple sections following Wikipedia structure
2. Use specific, descriptive section headings (e.g., "Background", "History", "Development", "Services", "Operations", "Technical specifications", "Impact", "Criticism", "Future plans")
3. Include an introduction, multiple main sections, and conclusion-style sections
4. Each section should have 2-3 paragraphs with specific details
5. Use clear markdown formatting with # for title and ## for sections
6. Write in an encyclopedic, factual style similar to Wikipedia
7. Aim for 1000-1500 words total
8. Include specific details, dates, numbers, and explanations
9. Avoid generic headings like "Overview" or "Introduction" - use specific descriptive titles

Format:
# {topic}

[Introduction paragraph with key facts]

## Background
[Historical context and background information]

## [Specific aspect like Development/History/Technology]
[Detailed content about this aspect]

## [Another specific aspect like Operations/Services/Impact]
[Content about this aspect]

## [Additional specific sections as relevant]
[Continue with domain-specific sections]

## [Future/Current status section]
[Information about current state and future plans]

Now write the article with specific, descriptive section headings:"""


def extract_storm_output(topic: str, storm_output_dir: str) -> str:
    topic_dir = Path(storm_output_dir) / topic.replace(" ", "_").replace("/", "_")
    output_files = [
        "storm_gen_article_polished.txt",
        "storm_gen_article.txt",
        "storm_gen_outline.txt",
    ]

    logger.debug(f"Looking for STORM output in: {topic_dir}")
    logger.debug(f"Directory exists: {topic_dir.exists()}")

    if topic_dir.exists():
        logger.debug(f"Directory contents: {list(topic_dir.iterdir())}")

    for filename in output_files:
        path = topic_dir / filename
        logger.debug(f"Checking file: {path}")
        logger.debug(f"File exists: {path.exists()}")

        if path.exists():
            try:
                content = path.read_text(encoding="utf-8")
                logger.debug(f"File content length: {len(content)}")
                logger.debug(f"Content preview: {content[:200]}...")

                if content.strip():
                    logger.info(f"Using STORM output from: {filename}")
                    return content
                else:
                    logger.warning(f"File {filename} is empty")
            except Exception as e:
                logger.warning(f"Could not read {path}: {e}")
        else:
            logger.debug(f"File does not exist: {path}")

    logger.error(f"No valid STORM output found for topic: {topic}")
    logger.error(f"Searched in directory: {topic_dir}")
    return f"# {topic}\n\nNo content generated by STORM."


def error_article(topic: str, error: Exception, method: str) -> Article:
    return Article(
        title=topic,
        content=f"# {topic}\n\nError: {str(error)}",
        sections={},
        metadata={"error": str(error), "method": method},
    )


def log_result(method: str, article: Article):
    if "error" in article.metadata:
        logger.warning(f"✗ {method} failed")
    else:
        wc = article.metadata.get("word_count", 0)
        logger.info(f"✓ {method} completed ({wc} words)")
