# FILE: runners/runner_utils.py
import logging
from pathlib import Path
from utils.data_models import Article
from baselines.llm_wrapper import OllamaLiteLLMWrapper
from config.model_config import ModelConfig
from utils.ollama_client import OllamaClient

logger = logging.getLogger(__name__)

def get_model_wrapper(client: OllamaClient, config: ModelConfig, task: str) -> OllamaLiteLLMWrapper:
    model = config.get_model_for_task(task)
    temp = config.get_temperature_for_task(task)
    return OllamaLiteLLMWrapper(client=client, model=model, temperature=temp)

def build_direct_prompt(topic: str) -> str:
    return f"""Write a comprehensive, well-structured article about \"{topic}\".

Requirements:
1. Create a detailed article with multiple sections
2. Include an introduction, at least 4-5 main sections, and a conclusion
3. Each section should have 2-3 paragraphs
4. Use clear markdown formatting with # for title and ## for sections
5. Write in an encyclopedic, informative style
6. Aim for 1000-1500 words total
7. Include specific details, examples, and explanations

Format:
# {topic}

[Introduction paragraph]

## [Section 1 Title]
[Content...]

## [Section 2 Title]
[Content...]

[Continue with more sections...]

## Conclusion
[Concluding paragraph]

Now write the article:"""

def extract_storm_output(topic: str, storm_output_dir: str) -> str:
    topic_dir = Path(storm_output_dir) / topic.replace(" ", "_").replace("/", "_")
    output_files = [
        "storm_gen_article_polished.txt",
        "storm_gen_article.txt",
        "storm_gen_outline.txt"
    ]
    for filename in output_files:
        path = topic_dir / filename
        if path.exists():
            try:
                content = path.read_text(encoding='utf-8')
                if content.strip():
                    logger.info(f"Using STORM output from: {filename}")
                    return content
            except Exception as e:
                logger.warning(f"Could not read {path}: {e}")
    return f"# {topic}\n\nNo content generated by STORM."

def error_article(topic: str, error: Exception, method: str) -> Article:
    return Article(
        title=topic,
        content=f"# {topic}\n\nError: {str(error)}",
        sections={},
        metadata={"error": str(error), "method": method}
    )

def log_result(method: str, article: Article):
    if "error" in article.metadata:
        logger.warning(f"✗ {method} failed")
    else:
        wc = article.metadata.get("word_count", 0)
        logger.info(f"✓ {method} completed ({wc} words)")
