#!/usr/bin/env python3
"""
Mock test for local STORM runner.
Tests the integration without requiring actual local models.
"""
import sys
import tempfile
from pathlib import Path
from unittest.mock import Mock

# Add src directory to path
src_dir = Path(__file__).parent.parent
if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

from utils.logging_setup import setup_logging


def create_mock_model_wrapper():
    """Create a mock model wrapper for testing."""
    mock_wrapper = Mock()
    mock_wrapper.model_path = "mock/model/path"
    mock_wrapper.generate = Mock(
        return_value="This is a mock article generated by the local model."
    )
    return mock_wrapper


def create_mock_local_runner():
    """Create a mock local baseline runner."""
    mock_runner = Mock()
    mock_runner.model_wrapper = create_mock_model_wrapper()
    return mock_runner


def test_storm_wrapper():
    """Test the LocalLiteLLMWrapper functionality."""
    print("🔧 Testing LocalLiteLLMWrapper...")

    from local_baselines.storm_runner import LocalLiteLLMWrapper

    # Create mock model wrapper
    mock_model = create_mock_model_wrapper()

    # Create LiteLLM wrapper
    wrapper = LocalLiteLLMWrapper(mock_model, temperature=0.7, max_tokens=512)

    # Test basic attributes
    assert wrapper.model_name == "mock/model/path"
    assert wrapper.temperature == 0.7
    assert wrapper.max_tokens == 512

    # Test message conversion
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Write about AI."},
    ]

    prompt = wrapper._messages_to_prompt(messages)
    expected = "System: You are a helpful assistant.\n\nUser: Write about AI."
    assert prompt == expected

    print("✅ LocalLiteLLMWrapper tests passed!")


def test_storm_runner_init():
    """Test LocalSTORMRunner initialization."""
    print("🔧 Testing LocalSTORMRunner initialization...")

    # Mock the import at the right location
    from unittest.mock import patch

    with patch("local.runner.LocalBaselineRunner") as mock_runner_class:
        mock_runner_class.return_value = create_mock_local_runner()

        from local_baselines.storm_runner import LocalSTORMRunner

        # Create temp directory for output
        with tempfile.TemporaryDirectory() as temp_dir:
            runner = LocalSTORMRunner(
                model_path="mock/models", output_manager=None, device="cpu"
            )

            assert runner.model_path == Path("mock/models")
            assert runner.device == "cpu"

    print("✅ LocalSTORMRunner initialization tests passed!")


def test_storm_config():
    """Test STORM configuration setup."""
    print("🔧 Testing STORM configuration...")

    from unittest.mock import patch

    with patch("local.runner.LocalBaselineRunner") as mock_runner_class, patch(
        "baselines.wikipedia_rm.WikipediaSearchRM"
    ) as mock_search:

        mock_runner_class.return_value = create_mock_local_runner()
        mock_search.return_value = Mock()

        from local_baselines.storm_runner import LocalSTORMRunner

        runner = LocalSTORMRunner()

        # Test configuration setup
        with tempfile.TemporaryDirectory() as temp_dir:
            storm_runner, config = runner.setup_storm_runner(temp_dir)

            # Verify default config
            assert config["max_conv_turn"] == 2
            assert config["max_perspective"] == 2
            assert config["search_top_k"] == 3
            assert config["max_thread_num"] == 1

            # Test custom config override
            custom_config = {"max_conv_turn": 3, "search_top_k": 5}
            storm_runner, config = runner.setup_storm_runner(temp_dir, custom_config)

            assert config["max_conv_turn"] == 3  # Overridden
            assert config["max_perspective"] == 2  # Default
            assert config["search_top_k"] == 5  # Overridden

    print("✅ STORM configuration tests passed!")


def main():
    """Run all mock tests."""
    setup_logging("INFO")
    print("🧪 Running Local STORM Mock Tests")
    print("=" * 50)

    try:
        test_storm_wrapper()
        test_storm_runner_init()
        test_storm_config()

        print("=" * 50)
        print("🎉 All mock tests passed!")
        print()
        print("Next steps:")
        print("1. Install local models in 'models/' directory")
        print("2. Run: python src/local/test_storm.py")
        print("3. Or run: python -m local --methods storm --topic_limit 1")

        return True

    except Exception as e:
        print(f"❌ Test failed: {e}")
        import traceback

        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
